### ISSUE TITLE
Specify buffer dynamically

### ISSUE THREAD

**Issue by Esgariot** [Iron-E/nvim-cartographer#10]
Hi, I'm new to lua and neovim, so I'm not really sure if one can dynamically type members, but docs could use an example where
buffer number is supplied dynamically, which could be used for LSP setup.

```lua
local map = require 'cartographer'

local servers = {...} -- server names

local on_attach = function (client, bufnr)
  local mml = map.nore.silent.buffer--<bufnr> ?
  mml.n['<leader><space>'] = '<cmd>lua vim.lsp.buf.hover()<CR>'
  
end

for _, s in ipairs(servers) do
	lsp[s].setup(coq.lsp_ensure_capabilities {
    on_attach =  on_attach
  })
end
```

**Comment by Iron-E** [comment]
You could do something like:

```lua
local mml = map.nore.silent['buffer'..bufnr]
```

That appends `bufnr` to the string "buffer". So if `bufnr` is 7, then you get "buffer7".

**Comment by Esgariot** [comment]
Thanks!
