### ISSUE TITLE
Syntax improvements

### ISSUE THREAD

**Issue by pedro757** [Iron-E/nvim-cartographer#8]
This works:
```lua
nnoremap['<leader>f']  = require'telescope.builtin'.fd
```

This does **not** work:
```lua
nnoremap['<leader>f']  = require'telescope.builtin'.fd({ previewer = false })
```
So I had to do this:

```lua
nnoremap['<leader>f']  = "<cmd>lua require'telescope.builtin'.fd({ previewer = false })<cr>"
```

which syntactically is worse in my opinion

**Comment by Iron-E** [comment]
What you're trying to do is described in the documentation [here](https://github.com/Iron-E/nvim-cartographer#lua-functions). 

tl;dr: The reason it isn't working for you is that the following is a function _call_:

```lua
require'telescope.builtin'.fd({ previewer = false })
```

So effectively, you're trying to map `<Leader>f` to the return of calling `fd` (which is probably nothing). What you want to do is:

```lua
nnoremap['<leader>f'] = function()
  require'telescope.builtin'.fd({ previewer = false })
end

-- as you say, this is also valid, but doesn't use your options. 
-- that's why we need the outer `function() end`
nnoremap['<leader>f'] = require'telescope.builtin'.fd
```

This creates a new function, that when called, calls `fd`. It is the type of `function` so cartographer knows what to do with it.

Hope this helps!

**Comment by pedro757** [comment]
hmm. I get it, that's the way lua works, thank you.
